// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	ID     string
	Token  string
	UserID string
}

type Session struct {
	ID           string
	StartTime    pgtype.Timestamptz
	EndTime      pgtype.Timestamptz
	InstructorID string
	StudentID    string
	Accepted     bool
}

type User struct {
	ID        string
	FirstName string
	LastName  string
	Username  string
	AboutMe   pgtype.Text
	Email     string
	Password  []byte
	Salt      string
	Deleted   bool
}
